/**
 * Opportunities Service
 * Reads opportunities from JSON file generated by GitHub Actions (updated every 12 hours)
 * Falls back to mock data if JSON is not available
 */

export interface Opportunity {
  id: string;
  title: string;
  company: string;
  location: string;
  salary?: string;
  type: string;
  description: string;
}

// Mock data as fallback
const mockOpportunities: Opportunity[] = [
  {
    id: '1',
    title: 'Senior React Developer',
    company: 'Tech Innovators',
    location: 'Asunción, Paraguay',
    salary: '$3,500 - $5,000 USD',
    type: 'Full-time',
    description: 'Buscamos un desarrollador React experimentado para liderar nuestro equipo frontend.',
  },
  {
    id: '2',
    title: 'Product Manager',
    company: 'Digital Solutions',
    location: 'Remoto',
    salary: '$2,500 - $4,000 USD',
    type: 'Full-time',
    description: 'Gestiona el roadmap de productos y lidera la estrategia de desarrollo.',
  },
  {
    id: '3',
    title: 'UX/UI Designer',
    company: 'Creative Studio',
    location: 'Asunción, Paraguay',
    salary: '$1,800 - $3,000 USD',
    type: 'Full-time',
    description: 'Diseña interfaces modernas y experiencias de usuario excepcionales.',
  },
  {
    id: '4',
    title: 'Data Scientist',
    company: 'Analytics Pro',
    location: 'Remoto',
    salary: '$3,000 - $5,500 USD',
    type: 'Full-time',
    description: 'Analiza datos complejos y desarrolla modelos predictivos.',
  },
  {
    id: '5',
    title: 'DevOps Engineer',
    company: 'Cloud Systems',
    location: 'Remoto',
    salary: '$2,800 - $4,500 USD',
    type: 'Full-time',
    description: 'Gestiona infraestructura en la nube y automatiza procesos de deployment.',
  },
  {
    id: '6',
    title: 'Marketing Manager',
    company: 'Brand Agency',
    location: 'Asunción, Paraguay',
    salary: '$2,000 - $3,500 USD',
    type: 'Full-time',
    description: 'Lidera estrategias de marketing digital y gestiona campañas.',
  },
];

/**
 * Fetch opportunities from GitHub Actions JSON output
 * Path: /data/opportunities.json (generated every 12 hours)
 */
export async function fetchOpportunities(): Promise<Opportunity[]> {
  try {
    // Try to fetch from public data directory (GitHub Actions output)
    const response = await fetch('/data/opportunities.json', {
      headers: {
        'Accept': 'application/json',
      },
    });

    if (response.ok) {
      const data = await response.json();
      
      // Validate that we have an array of opportunities
      if (Array.isArray(data) && data.length > 0) {
        return data;
      }
    }
  } catch (error) {
    console.warn('Failed to fetch opportunities from JSON:', error);
  }

  // Fallback to mock data
  console.log('Using mock opportunities data');
  return mockOpportunities;
}

/**
 * Get opportunities with caching
 * Useful for avoiding repeated fetches during component lifecycle
 */
let cachedOpportunities: Opportunity[] | null = null;
let cacheTimestamp: number = 0;
const CACHE_DURATION = 5 * 60 * 1000; // 5 minutes

export async function getOpportunitiesWithCache(): Promise<Opportunity[]> {
  const now = Date.now();

  // Return cached data if still valid
  if (cachedOpportunities && now - cacheTimestamp < CACHE_DURATION) {
    return cachedOpportunities;
  }

  // Fetch fresh data
  cachedOpportunities = await fetchOpportunities();
  cacheTimestamp = now;

  return cachedOpportunities;
}
